# FROM https://github.com/marcelbirkner/docker-ci-tool-stack/blob/master/docker-compose.yml
version: '3'

services:
   nexus:
      image: sonatype/nexus3
      ports:
         - "8081:8081"
      networks:
         - nexusnetwork
      volumes:
         - nexus-data:/nexus-data

volumes:
   nexus-data:

networks:
   nexusnetwork:
      driver: bridge

